repository:
  name: cookies
  description: Load and save cookies within your Web application
  private: false
  default_branch: main
  allow_auto_merge: true
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - 'Test'
          - 'CodeQL'
          - 'Analyze (javascript-typescript) (dynamic)'
      enforce_admins: true
      required_linear_history: true
      required_signatures: true
      required_conversation_resolution: true
      restrictions: null
